### PR TITLE
Make computation of bounding boxes safer

### LINKED ISSUE #1312: "Pan to Origin" on an empty patch breaks patchboard
### Environment

- Scope: desktop IDE, browser IDE
- Version: 0.21.2

### Steps to reproduce

1. Create/open an empty patch
2. Select `View -> Pan to Origin` from the menu or press the equivalent shortcut

### Expected behavior

Nothing(?)

### Actual behavior

Errors in the console, further interactions with patchboard(panning etc) break.

### Console output

```
Error: <pattern> attribute x: Expected length, "-Infinity".
Error: <pattern> attribute y: Expected length, "-Infinity".
Error: <g> attribute transform: Expected number, "…rix(1, 0, 0, 1, -Infinity, -Infi…".
```

### PR DESCRIPTION
**Pull request by evgenykochetkov**
Fixes #1312

### CODE REVIEW

File: packages/xod-client/src/project/nodeLayout.js [hunk 1]
```diff
@@ -160,34 +162,39 @@ export const snapNodeSizeToSlots = R.compose(
...
-// :: ([Number] -> Number) -> ([Number] -> Number) -> [Position] -> Position
+// :: ([Number] -> Number) -> ([Number] -> Number) -> [Position] -> Maybe Position
 export const findPosition = R.uncurryN(3)((xFn, yFn) =>
-  R.converge((x, y) => ({ x, y }), [
-    R.compose(xFn, R.map(R.prop('x'))),
-    R.compose(yFn, R.map(R.prop('y'))),
-  ])
+  R.ifElse(
+    R.isEmpty,
+    R.always(Maybe.Nothing()),
```
Comment (brusherru) [inline packages/xod-client/src/project/nodeLayout.js]: Just `Maybe.Nothing,`?
