### PR TITLE
Do not save terminal patches for custom types

### LINKED ISSUE #1593: Do NOT save terminals for users custom types
### Environment
* Scope: desktop IDE
* Version: 0.25.3

### Steps to reproduce
1.  Create new project
2.  Create patch `a` and place `output-self` and `not-implemented-in-xod`
3.  Save project as a multi-file project

### Expected behavior
On FS in the project directory, we will see two directories: `main`, `a` and `project.xod` file.

### Actual behavior
It also saves `input-a` and `output-a`.

**Interesting thing**
If you delete it manually and then reload project and save again — it will not be saved again. So it reproduces only on the first saving of the project.

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #1593

### CODE REVIEW

File: packages/xod-fs/src/unpack.js [hunk 1]
```diff
@@ -55,6 +55,7 @@ export const arrangeByFiles = def(
     ];
     const patchFiles = R.compose(
       R.chain(arrangePatchByFiles),
+      R.reject(XP.isCustomTypeTerminalPatch),
```
Comment (evgenykochetkov) [inline packages/xod-fs/src/unpack.js]: Why not perform the check using `isGenuinePatch`?
