### PR TITLE
Fix crash of two linked jumper nodes

### LINKED ISSUE #1671: Linking two jumpers crashes IDE
### Environment

* Scope: desktop IDE
* Version: dev 6075380f3fe229c50f10176b42cf1f1a3f9234b1

### Steps to reproduce

1.  Place two `jumper` nodes onto a patch
2.  Link the first one to the second

### Expected behavior

The nodes get linked with a gray link

### Actual behavior

IDE goes to the gray screen of death, recovery impossible

### Console output

```
Uncaught TypeError: invalid type given to Either.either
    at either (bundle.js:121158)
    at bundle.js:35013
    at bundle.js:12707
    at bundle.js:114694
    at bundle.js:12707
    at bundle.js:115075
    at bundle.js:12706
    at JumperNodeBody (bundle.js:196518)
    at updateFunctionalComponent (bundle.js:105781)
    at beginWork (bundle.js:106185)
bundle.js:107709 The above error occurred in the <JumperNodeBody> component:
    in JumperNodeBody (created by TooltipHOC)
    in g (created by TooltipHOC)
    in svg (created by TooltipHOC)
    in TooltipHOC (created by Node)
    in Node (created by NodesLayer)
    in g (created by NodesLayer)
    in NodesLayer (created by shouldUpdate(NodesLayer))
    in shouldUpdate(NodesLayer) (created by Patch)
    in g (created by Patch)
    in svg (created by PatchSVG)
    in PatchSVG (created by Patch)
    in div (created by FocusTrap)
    in FocusTrap (created by HotKeys)
    in HotKeys (created by Patch)
    in div (created by Patch)
    in Patch (created by DropTarget(Patch))
    in DropTarget(Patch) (created by Connect(DropTarget(Patch)))
    in Connect(DropTarget(Patch)) (created by Editor)
    in div (created by Editor)
    in div (created by FocusTrap)
    in FocusTrap (created by Editor)
    in div (created by FocusTrap)
    in FocusTrap (created by HotKeys)
    in HotKeys (created by Editor)
    in Editor (created by DragDropContext(Editor))
    in DragDropContext(Editor) (created by Connect(DragDropContext(Editor)))
    in Connect(DragDropContext(Editor)) (created by App)
    in div (created by FocusTrap)
    in FocusTrap (created by HotKeys)
    in HotKeys (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider (created by Root)
    in Root

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ bundle.js:107709
bundle.js:108956 Uncaught TypeError: invalid type given to Either.either
    at either (bundle.js:121158)
    at bundle.js:35013
    at bundle.js:12707
    at bundle.js:114694
    at bundle.js:12707
    at bundle.js:115075
    at bundle.js:12706
    at JumperNodeBody (bundle.js:196518)
    at updateFunctionalComponent (bundle.js:105781)
    at beginWork (bundle.js:106185)
```

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #1671.

### CODE REVIEW

File: packages/xod-client/src/project/components/nodeParts/JumperNodeBody.jsx [hunk 1]
```diff
@@ -2,31 +2,27 @@ import R from 'ramda';
...
-    [
-      () => outConnected,
-      R.compose(
-        foldEither('error', R.identity),
-        R.path([OUTPUT_PINKEY, 'deducedType'])
-      ),
-    ],
+    [() => inConnected, getDeducedTypeOfPin(INPUT_PINKEY)],
+    [() => outConnected, getDeducedTypeOfPin(OUTPUT_PINKEY)],
     [R.T, R.always('')],
```
Comment (evgenykochetkov) [inline packages/xod-client/src/project/components/nodeParts/JumperNodeBody.jsx]: Should this default to `'generic'` too?

Comment (brusherru) [reply packages/xod-client/src/project/components/nodeParts/JumperNodeBody.jsx]: It does not make sense, but I'll do it to avoid questions in the future :)
