### PR TITLE
Fix compiling and uploading to boards with multiple cpu variants (like Arduino Nano)

### LINKED ISSUE #719: Error when compiling for Arduino Nano
### Steps to reproduce

1. Open `welcome-to-xod` project
2. Deploy → Upload to Arduino
3. Select `Arduino Nano` as target board
4. Click upload

### Expected behavior

Upload succeeds

### Actual behavior

Oops! Error occured.

```
avr-g++: error: missing device or architecture after '-mmcu='
exit status 1
"/opt/XOD IDE/resources/arduino-builder/arduino-builder" -hardware="/opt/XOD IDE/resources/arduino-builder/hardware" -hardware="/home/abaddon/.config/xod-client-electron/packages" -tools="/opt/XOD IDE/resources/arduino-builder/tools" -tools="/home/abaddon/.config/xod-client-electron/packages" -fqbn="arduino:avr:nano" -build-path="/home/abaddon/.config/xod-client-electron/upload-temp/build" "/home/abaddon/.config/xod-client-electron/upload-temp/xod-arduino-sketch.cpp" (exited with error code 1)
```

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #719.

### CODE REVIEW

File: packages/xod-arduino-deploy/src/boardsParser.js [hunk 1]
```diff
@@ -13,7 +13,19 @@ import * as Utils from './utils';
...
+      R.when(
+        R.both(
+          R.propEq(1, 'menu'),
+          R.compose(R.equals(4), R.length)
+        ),
+        R.append('cpuName')
+      )
+    )(tokens),
+    {}
+  ),
```
Comment (evgenykochetkov) [inline packages/xod-arduino-deploy/src/boardsParser.js]: I only understood why all of this is happening because you showed me the example yesterday 🙈
A docstring with some example/explanation would be really nice here.

File: packages/xod-arduino-deploy/src/boardsParser.js [hunk 2]
```diff
@@ -42,19 +54,44 @@ const loadBoards = R.curry(
 //
 // =============================================================================
 
+// :: FQBN -> Map boardIdentifier BoardPrefs -> BoardPrefs
+const pickBoardPrefsByFqbn = R.curry(
```
Comment (nkrkv) [inline packages/xod-arduino-deploy/src/boardsParser.js]: I’d name it `getBoardPrefsByFqbn` because `pick` is already exploited by Ramda with a different semantics

File: packages/xod-arduino-deploy/src/boardsParser.js [hunk 3]
```diff
@@ -42,19 +54,44 @@ const loadBoards = R.curry(
...
+  (fqbn, boardPrefsMap) => {
+    const pabc = Utils.parseFQBN(fqbn);
+    const getCpuPrefs = R.path(['menu', 'cpu', pabc.cpu]);
```
Comment (nkrkv) [inline packages/xod-arduino-deploy/src/boardsParser.js]: If you’d use `R.pathOr(['menu', 'cpu', pabc.cpu], {})` you can get rid of `R.when` with duplication below. This would make the code more linear and clear.

File: packages/xod-arduino-deploy/test/fixtures/packages/arduino/hardware/samd/boards.txt [hunk 4]
```diff
@@ -368,3 +368,53 @@ tian_cons.pid.0=0xEA70
 tian_cons.descriptor.0=Standard Com Port
 tian_cons.hide=true
 tian_cons.build.board=SAMD_TIAN
+
+
+##############################################################
+# FOR TESTING OF MULTIPLE CPU MENU
+# NEXT LINES WAS COPIED FROM AVR ARCHITECTURE
+##############################################################
```
Comment (nkrkv) [inline packages/xod-arduino-deploy/test/fixtures/packages/arduino/hardware/samd/boards.txt]: ~OF~
~WAS~ WERE

And I think the whole idea is fragile. Take samd… override with avr… a bit of mess.

Wouldn’t it better to simply take AVR txt or it’s part and place it in a separate fixture?

**Comment by brusherru** [comment]
@nkrkv @evgenykochetkov it's done! Check it out, please
