### PR TITLE
fix(xod-client): fix error when closing last opened tab

### LINKED ISSUE #817: Last tab do not close until clicked again
### Steps to reproduce

1. Open a project
2. Close the single opened tab

### Expected behavior

The tab closes, I see XOD watermark

### Actual behavior

* The patch canvas stays intact
* Tab tip disappears
* If I’d click on the patch canvas it actually closes

### Console output

```
Uncaught TypeError: Cannot read property 'breadcrumbs' of null
    at prop (file:///home/nailxx/devel/xod/packages/xod-client-electron/src-babel/bundle.js:32659:61)
    at file:///home/nailxx/devel/xod/packages/xod-client-electron/src-babel/bundle.js:31636:47
    at f1 (file:///home/nailxx/devel/xod/packages/xod-client-electron/src-babel/bundle.js:31509:18)
    at file:///home/nailxx/devel/xod/packages/xod-client-electron/src-babel/bundle.js:34164:15
    at file:///home/nailxx/devel/xod/packages/xod-client-electron/src-babel/bundle.js:31802:50
    at file:///home/nailxx/devel/xod/packages/xod-client-electron/src-babel/bundle.js:34164:28
    at file:///home/nailxx/devel/xod/packages/xod-client-electron/src-babel/bundle.js:31802:50
    at file:///home/nailxx/devel/xod/packages/xod-client-electron/src-babel/bundle.js:135669:28
    at Array.map (native)
    at selector (file:///home/nailxx/devel/xod/packages/xod-client-electron/src-babel/bundle.js:135668:34)
```

### PR DESCRIPTION
**Pull request by evgenykochetkov**
Closes #817

### CODE REVIEW

**Comment by evgenykochetkov** [comment]
Nice catch!
Looks like it broke for some other reason after rebase on fresh master with #815 merged.

File: packages/xod-client/src/project/selectors.js [hunk 1]
```diff
@@ -149,10 +144,13 @@ const addDeadFlag = R.curry(
...
 // :: State -> StrMap RenderableNode
 export const getRenderableNodes = createMemoizedSelector(
-  [getProject, getCurrentPatchUnsafe, getCurrentPatchNodes, getConnectedPins],
+  [getProject, getCurrentPatch, getCurrentPatchNodes, getConnectedPins],
   [R.T, R.equals, R.equals, R.equals],
-  (project, currentPatch, currentPatchNodes, connectedPins) =>
-    R.map(
+  (project, maybeCurrentPatch, currentPatchNodes, connectedPins) => {
+    if (Maybe.isNothing(maybeCurrentPatch)) return {};
+    const currentPatch = explode(maybeCurrentPatch);
```
Comment (nkrkv) [inline packages/xod-client/src/project/selectors.js]: Uff imperative. Isn’t it better to `foldMaybe`?

Comment (brusherru) [reply packages/xod-client/src/project/selectors.js]: Yep, it's better. Coming soon.
