### PR TITLE
Сheck for dead links more strictly

### LINKED ISSUE #1105: IDE crashes with “Cannot read property 'type' of undefined” on some patches
### Steps to reproduce

1. Open project [obstacle-avoidance.zip](https://github.com/xodio/xod/files/1780364/obstacle-avoidance.zip)
2. Find the `buffer-4` node, double-click to open

### Expected behavior

The patch is opened or a clear error is shown. IDE stays alive

### Actual behavior

The IDE window goes white, dies forever

### Console output

Seems too truncated but can give some idea:

```
Uncaught TypeError: Cannot read property 'type' of undefined
    at selectors.js:287
    at XWrap.f (map.js:53)
    at XWrap.module.exports.XWrap.@@transducer/step (_xwrap.js:10)
    at _arrayReduce (_reduce.js:11)
    at _reduce (_reduce.js:44)
    at map (map.js:52)
    at _dispatchable.js:39
    at _curry2.js:20
    at f1 (_curry1.js:17)
    at _pipe.js:3
(anonymous) @ selectors.js:287
(anonymous) @ map.js:53
module.exports.XWrap.@@transducer/step @ _xwrap.js:10
_arrayReduce @ _reduce.js:11
_reduce @ _reduce.js:44
map @ map.js:52
(anonymous) @ _dispatchable.js:39
(anonymous) @ _curry2.js:20
f1 @ _curry1.js:17
(anonymous) @ _pipe.js:3
(anonymous) @ _arity.js:5
(anonymous) @ selectors.js:263
(anonymous) @ selectorTools.js:28
(anonymous) @ selectorTools.js:26
_map @ _map.js:6
map @ map.js:57
(anonymous) @ _dispatchable.js:39
f2 @ _curry2.js:25
(anonymous) @ selectorTools.js:26
apply @ apply.js:25
f2 @ _curry2.js:25
(anonymous) @ applySpec.js:42
(anonymous) @ map.js:53
module.exports.XWrap.@@transducer/step @ _xwrap.js:10
_arrayReduce @ _reduce.js:11
_reduce @ _reduce.js:44
map @ map.js:52
(anonymous) @ _dispatchable.js:39
f2 @ _curry2.js:25
(anonymous) @ applySpec.js:42
(anonymous) @ _curryN.js:37
(anonymous) @ _arity.js:6
computeStateProps @ connect.js:146
updateStatePropsIfNeeded @ connect.js:204
render @ connect.js:340
finishClassComponent @ react-dom.development.js:7873
updateClassComponent @ react-dom.development.js:7850
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
react-dom.development.js:9747 The above error occurred in the <Connect(DragDropContext(Editor))> component:
    in Connect(DragDropContext(Editor)) (created by App)
    in div (created by FocusTrap)
    in FocusTrap (created by HotKeys)
    in HotKeys (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider (created by Root)
    in Root

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:9747
captureError @ react-dom.development.js:10540
renderRoot @ react-dom.development.js:10391
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
selectors.js:287 Uncaught TypeError: Cannot read property 'type' of undefined
    at selectors.js:287
    at XWrap.f (map.js:53)
    at XWrap.module.exports.XWrap.@@transducer/step (_xwrap.js:10)
    at _arrayReduce (_reduce.js:11)
    at _reduce (_reduce.js:44)
    at map (map.js:52)
    at _dispatchable.js:39
    at _curry2.js:20
    at f1 (_curry1.js:17)
    at _pipe.js:3
```

### PR DESCRIPTION
**Pull request by evgenykochetkov**
Closes #1105

### CODE REVIEW

File: packages/xod-project/src/patch.js [hunk 1]
```diff
@@ -934,23 +934,27 @@ export const upsertDeadPins = def(
...
+        )
       )
     );
 
     return R.compose(
       R.merge(pins),
       R.indexBy(Pin.getPinKey),
-      R.when(
-        R.complement(R.isEmpty),
+      R.unless(
```
Comment (brusherru) [inline packages/xod-project/src/patch.js]: 👍

File: packages/xod-project/src/patch.js [hunk 2]
```diff
@@ -934,23 +934,27 @@ export const upsertDeadPins = def(
...
-    })(R.values(pins));
+
+    const pinsByDir = R.compose(R.groupBy(Pin.getPinDirection), R.values)(pins);
 
     const rejectNondeadLinks = R.reject(
       R.either(
-        R.compose(isAmong(pinKeys), Link.getLinkInputPinKey),
-        R.compose(isAmong(pinKeys), Link.getLinkOutputPinKey)
+        R.both(
+          R.pipe(Link.getLinkInputNodeId, R.equals(nodeId)),
```
Comment (brusherru) [inline packages/xod-project/src/patch.js]: Could be replaced with `Link.isLinkInputNodeIdEquals(nodeId)` and the same for output...

Comment (evgenykochetkov) [reply packages/xod-project/src/patch.js]: Oh, right. Done!
