### PR TITLE
Fix implementation of the placement new operator

### LINKED ISSUE #1866: Extend the placement `new` operator conditions
### Steps to reproduce

The conditions of the placement `new` operator in XOD should be extended for Arduino MKR boards with Atmel's SAMD21 processor.

The list of exposed Arduino boards:
Arduino MKR1000, MKRZero boards.

To reproduce the error place any Hardware UART node onto the blank patch and flash the program for mentioned Arduino boards.

### Actual behavior
```
/tmp/xod_temp_sketchbookIE7zw0/xod_1569851898943_sketch/xod_1569851898943_sketch.ino: In function 'void xod::xod__uart__uart::evaluate(xod::xod__uart__uart::Context)':
/tmp/xod_temp_sketchbookIE7zw0/xod_1569851898943_sketch/xod_1569851898943_sketch.ino:1065:65: error: no matching function for call to 'operator new(sizetype, uint8_t [16])'
         state->uart = new (state->mem) HardwareUart(serial, baud); 
                                                                 ^`
<built-in>: note: candidate: void* operator new(unsigned int)
<built-in>: note:   candidate expects 1 argument, 2 provided

/tmp/xod_temp_sketchbookIE7zw0/xod_1569851898943_sketch/xod_1569851898943_sketch.ino: In function 'void xod::xod__uart__uart_1::evaluate(xod::xod__uart__uart_1::Context)':
/tmp/xod_temp_sketchbookIE7zw0/xod_1569851898943_sketch/xod_1569851898943_sketch.ino:1241:97: error: no matching function for call to 'operator new(sizetype, uint8_t [16])'
         state->uart = new (state->mem) HardwareUart(Serial1, (uint32_t)getValue<input_BAUD>(ctx));
                                                                                                ^
<built-in>: note: candidate: void* operator new(unsigned int)
<built-in>: note:   candidate expects 1 argument, 2 provided
```

### How to fix 
Add the condition to the `xod/packages/xod-arduino/platform/memoty.h`:

```
#ifdef __AVR__ || ARDUINO_ARCH_SAMD
// Placement `new` for Arduino
void* operator new(size_t, void* ptr) {
    return ptr;
}
#endif
```

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #1866 and the bug reported on the [forum](https://forum.xod.io/t/xod-0-32-0-released-introducing-cloud-feeds/3006/2) (operator was added in arduino:avr 1.8.2).

### CODE REVIEW

File: packages/xod-arduino/platform/memory.h [hunk 1]
```diff
@@ -5,9 +5,10 @@
  *
  *
  =============================================================================*/
-#ifdef __AVR__
-// Placement `new` for Arduino
+
+// Support a placment new operator on platforms that does not have
```
Comment (nkrkv) [inline packages/xod-arduino/platform/memory.h]:
```suggestion
// Support a placement new operator on platforms that do not have
```

File: packages/xod-arduino/platform/memory.h [hunk 2]
```diff
@@ -5,9 +5,10 @@
...
+// an implementation of the placement new operator
```
Comment (nkrkv) [inline packages/xod-arduino/platform/memory.h]:
```suggestion
// its implementation
```

File: workspace/blink/__fixtures__/arduino.cpp [hunk 3]
```diff
@@ -419,12 +419,16 @@ class XStringCString : public XString {
  *
  *
  =============================================================================*/
-#ifdef __AVR__
-// Placement `new` for Arduino
+
+// Hack: In version 1.8.2 of arduino:avr package was added a placement new operator
+// #define __AVR__GTE__1_8_2__ (defined(__AVR__) && !defined(bitToggle))
+
+// #if __AVR__GTE__1_8_2__ || defined(ARDUINO_ARCH_SAMD)
```
Comment (nkrkv) [inline workspace/blink/__fixtures__/arduino.cpp]: Obsolete? The same for other `__fixture__`’s

File: packages/xod-arduino/platform/memory.h [hunk 4]
```diff
@@ -5,9 +5,9 @@
  *
  *
  =============================================================================*/
-#ifdef __AVR__
-// Placement `new` for Arduino
-void* operator new(size_t, void* ptr) {
+
+// Support a placement new operator
```
Comment (nkrkv) [inline packages/xod-arduino/platform/memory.h]:
```suggestion
// Define the placement new operator for cores that do not provide their own.
// Note, this definition takes precedence over the existing one (if any). We found no C++ way
// to use the existing implementation _and_ this implementation if not yet defined.
```
