### PR TITLE
Detect pin name clashes

### LINKED ISSUE #1337: Detect pin name clashes
### Steps to reproduce

1. Create a new patch `foo`
2. Add an input pulse and output pulse
3. Give both label `X`
4. Switch to `main` and add two `foo` nodes
5. Make a link between them
6. Hit Deploy → Show Code for Arduino

[same-name-pins.zip](https://github.com/xodio/xod/files/2171079/same-name-pins.zip)

### Expected behavior

- A message is shown telling that pins of a particular node can’t have the same nodes

### Actual behavior

Nothing

### Console output

```
Uncaught TypeError: undefined does not have a method named "split"
    at invoker.js:40
    at _curryN.js:37
    at _arity.js:5
    at _pipe.js:3
    at _arity.js:5
    at _pipe.js:3
    at _arity.js:5
    at converge.js:41
    at _map (_map.js:6)
    at converge.js:40
(anonymous) @ invoker.js:40
(anonymous) @ _curryN.js:37
(anonymous) @ _arity.js:5
(anonymous) @ _pipe.js:3
(anonymous) @ _arity.js:5
(anonymous) @ _pipe.js:3
(anonymous) @ _arity.js:5
(anonymous) @ converge.js:41
_map @ _map.js:6
(anonymous) @ converge.js:40
f1 @ _curry1.js:17
(anonymous) @ _pipe.js:3
(anonymous) @ _arity.js:5
_ifElse @ ifElse.js:33
f1 @ _curry1.js:17
(anonymous) @ index.js:2491
(anonymous) @ index.js:860
(anonymous) @ templates.js:163
(anonymous) @ VM166:5
prog @ handlebars.js:1259
execIteration @ handlebars.js:726
(anonymous) @ handlebars.js:736
(anonymous) @ VM171:7
prog @ handlebars.js:1259
execIteration @ handlebars.js:726
(anonymous) @ handlebars.js:736
(anonymous) @ VM194:6
main @ handlebars.js:1213
ret @ handlebars.js:1216
ret @ handlebars.js:3488
(anonymous) @ templates.js:284
(anonymous) @ index.js:2491
(anonymous) @ index.js:860
(anonymous) @ templates.js:295
(anonymous) @ index.js:2491
(anonymous) @ index.js:860
_Right.map @ Either.js:59
(anonymous) @ _dispatchable.js:30
(anonymous) @ _curry2.js:20
f1 @ _curry1.js:17
(anonymous) @ _pipe.js:3
(anonymous) @ _pipe.js:3
(anonymous) @ _arity.js:4
onShowCodeArduino @ App.jsx:43
apply @ /home/nailxx/devel/xod/node_modules/electron/dist/resources/electron.asar/common/api/callbacks-regi…:48
(anonymous) @ /home/nailxx/devel/xod/node_modules/electron/dist/resources/electron.asar/renderer/api/remote.js:299
emitThree @ events.js:116
emit @ events.js:194
```

### How to fix

Pin name clashing should be checked as a part of patch validation. If matches found an error¹ should be shown on transpilation. Furthermore, the terminals, pins, and nodes might be marked as error’ish in real-time. Bars below denote the desired tooltip text.

¹
```markdown
**Pin names conflict**
@/main > @/foo: |Multiple pins with label `X` found on in the patch node|. Pin names
must be unique.
Assign either of conflicting terminals another label.
```

It’s important to check *normalized* pin labels to make sure the scenarios when an input takes an auto-generated name `IN3` and manually named output `IN3` are not possible.

### PR DESCRIPTION
**Pull request by evgenykochetkov**
Closes #1337

Plus a tiny bit of refactoring in `xod-client`'s `project` selectors.

### CODE REVIEW

File: packages/xod-project/src/project.js [hunk 1]
```diff
@@ -666,35 +657,51 @@ export const validatePatchContents = def(
...
+ * Checks `patch` content to be valid:
+ *
+ * - all nodes have existent types (patches),
+ * - valid pinKeys in the links
+ * @function validatePatchContents
+ * @param {Patch} patch
+ * @param {Project} project
+ * @returns {Either<Error|Patch>}
+ */
+// TODO: Try to simplify this mess :-D
```
Comment (nkrkv) [inline packages/xod-project/src/project.js]: You’ve simplified the mess :+1: I think this comment should go.

File: packages/xod-project/src/messages.js [hunk 2]
```diff
@@ -235,6 +235,12 @@ export default {
     note: `Can't find the Pin "${pinKey}" in the patch with path "${patchPath}"`,
     trace,
   }),
+  CLASHING_PIN_LABELS: ({ label, pinKeys, trace }) => ({
+    title: 'Clashing pin names',
+    note: `${pinKeys.length} pins are named ${label}`,
+    solution: 'Give pins unique names',
```
Comment (nkrkv) [inline packages/xod-project/src/messages.js]: Give the pins

**Comment by evgenykochetkov** [comment]
Done.
But I'm not sure about the result.
screen shot 2018-07-13 at 16 45 02
screen shot 2018-07-13 at 16 45 28
Is this good user experience?
