### PR TITLE
Fix tab sorting

### LINKED ISSUE #802: Fix tab sorting behaviour
### Steps to reproduce

let's say we have 4 open tabs:
```
aa  bb  cc  dd
```

and drag `dd` between `aa` and `bb`:
```
   dd
   |
aa V bb cc
```

### Expected tab order

```
aa dd bb cc
```

### Actual tab order

```
aa dd cc bb 
```
`bb` is just swapped with `dd`

### How to fix

See here: https://github.com/xodio/xod/blob/master/packages/xod-client/src/editor/containers/Tabs.jsx#L79

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #802

### CODE REVIEW

File: packages/xod-client/src/editor/containers/Tabs.jsx [hunk 1]
```diff
@@ -75,8 +73,12 @@ class Tabs extends React.Component {
...
-  onSortEnd(changes) {
-    const sortedTabs = swap(changes.oldIndex, changes.newIndex, this.getTabs());
+  onSortEnd({ oldIndex, newIndex }) {
+    const tabs = this.getTabs();
+    const sortedTabs = R.compose(
+      R.insert(newIndex, tabs[oldIndex]),
+      R.remove(oldIndex, 1)
+    )(tabs);
     const newTabs = assocIndexes(sortedTabs);
     const indexedTabs = indexById(newTabs);
```
Comment (evgenykochetkov) [inline packages/xod-client/src/editor/containers/Tabs.jsx]: No need for these intermediate constants anymore, it all can be in one `compose`

Comment (brusherru) [reply packages/xod-client/src/editor/containers/Tabs.jsx]: Done!
