### PR TITLE
Do not load project with invalid patch paths

### LINKED ISSUE #2097: XOD IDE loads libraries with invalid patch paths
### Steps to reproduce
1. Open any project (with at least one patch)
2. Save the project in the `YOUR_WORKSPACE/__lib__/somebody` directory as a multifile project and name it with uppercase symbols. E.G. `YOUR_WORKSPACE/__lib__/somebody/UpercaseSymbolsIsForbidden`
3. Open any other project
4. Save it as a xodball
5. Try to open this xodball

### Expected behavior

- IDE opens a xodball.
- There is no `somebody/UppercaseSymbolsIsForbidden` library in the project browser.
- IDE shows an error message on the IDE start, which tells the user that some of the libraries have invalid names.

### Actual behavior

- IDE does not open a xodball, because it has `INVALID_XODBALL_FORMAT`
- Xodball contains a patch(es) with path `somebody/UppercaseSymbolsIsForbidden/patch-name`
- Project browser does not contain an invalid library

### How to fix 

1. Do not load libraries with an invalid username, project name, or patch names.
2. Show an error message on IDE start if such libraries have been found.

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #2097

### CODE REVIEW

File: packages/xod-fs/src/messages.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import { PROJECT_LOADED_WITH_INVALID_PATCH_PATHS } from './errorCodes';
+
+export default {
+  [PROJECT_LOADED_WITH_INVALID_PATCH_PATHS]: ({ patchPaths }) => ({
+    title: 'Can not load some patches',
```
Comment (nkrkv) [inline packages/xod-fs/src/messages.js:5]:
```suggestion
    title: 'Cannot load some patches',
```

File: packages/xod-fs/src/messages.js [hunk 2]
```diff
@@ -0,0 +1,10 @@
...
+    note: `Some patches have an invalid patch paths: ${patchPaths.join(', ')}`,
```
Comment (nkrkv) [inline packages/xod-fs/src/messages.js:6]: I’d limit this array with an ellipsis if more than, say, three items. Otherwise, UI will explode

File: packages/xod-fs/src/messages.js [hunk 3]
```diff
@@ -0,0 +1,10 @@
...
+    solution:
+      'Open the "__lib__" directory in your workspace and ensure that listed directory names is valid. Only lowercase latin alphabet, numbers and minus between other symbols are alowed.',
```
Comment (nkrkv) [inline packages/xod-fs/src/messages.js:8]:
```suggestion
      'Open the "__lib__" directory in your workspace and ensure that listed directory names are valid. Only lowercase latin alphabet, numbers, and hyphens are allowed.',
```

**Review by nkrkv — CHANGES_REQUESTED** [review]

File: packages/xod-fs/src/messages.js [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+);
+
+export default {
+  [PROJECT_LOADED_WITH_INVALID_PATCH_PATHS]: ({ patchPaths }) => ({
+    title: 'Cannot load some patches',
+    note: `Some patches have an invalid patch paths: ${formatPatchPaths(
+      patchPaths
+    )}`,
+    solution:
+      'Open the "__lib__" directory in your workspace and ensure that listed directory names are valid. Only lowercase latin alphabet, numbers, and hypens are alowed.',
```
Comment (nkrkv) [inline packages/xod-fs/src/messages.js:19]:
```suggestion
      'Open the "__lib__" directory in your workspace and ensure that listed directory names are valid. Only lowercase latin alphabet, numbers, and hypens are allowed.',
```

**Review by nkrkv — APPROVED** [review]
:+1: 

See one more typo below though

**Review by evgenykochetkov — APPROVED** [review]
LGTM!
