### PR TITLE
Handle cloud compilation errors

### LINKED ISSUE #1781: Bad handling of cloud compilation errors
### Environment

* Scope: desktop IDE, browser IDE
* Version: 0.28.0-master
* OS: any
* Machine: any

### Steps to reproduce

1.  Run simulation/tabtest many times until it fails

### Expected behavior

Error message with an actual reason of the error shows in console (serial tab).

### Actual behavior

image

### How to fix

There are many things can go wrong. Proposed solution:

| If... | ...then show message... |
| ---- | --- |
| Network error | fetch error message (already done) |
| HTTP code 200 | `body.logs[].stderr` (red) and `body.logs[].stdout` |
| HTTP code 200, can't load js/wasm | fetch error message |
| HTTP code 422 | WASM_COMPILATION_ERROR |
| HTTP code 402 | Limit exceeded message (this is optional) |
| Other HTTP codes | just print formatted body (if json) or print body (strip html tags?) |

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #1781

### CODE REVIEW

File: packages/xod-cloud-compile/src/compile.js [hunk 1]
```diff
@@ -46,9 +46,16 @@ const compile = R.curry((hostname, accessToken, suite, opts) => {
     )
     .then(res => {
       if (!res.ok) {
-        return res.json().then(json => Promise.reject(
-          createError(EC.WASM_COMPILATION_ERROR, json)
-        ));
+        return res.json()
```
Comment (knopki) [inline packages/xod-cloud-compile/src/compile.js]: LGTM, except uncatched JSON parsing error.

Comment (brusherru) [reply packages/xod-cloud-compile/src/compile.js]: Nice catch! Just fixed it.
