### PR TITLE
Preserve patch offset when starting debugger

### LINKED ISSUE #1012: When debugger starts patch offset should be preserved
### Steps to reproduce

1. Create a patch with a sensor and `watch`
2. Select all, move down, pan, move down… 1.5-2 screens at total
3. Upload with debugger
4. Wait for the debugger to start

### Expected behavior

- The nodes are visible
- They are only offset down a bit to contain the breadcrumbs line (see #1011)

### Actual behavior

- I see an empty canvas, I’m lost
- If I stop debug, I still see the empty canvas
- That’s hard to understand intuitively, but the nodes are 1.5-2 screens to the bottom

### PR DESCRIPTION
**Pull request by evgenykochetkov**
Closes #1012

### CODE REVIEW

File: packages/xod-client/src/editor/reducer.js [hunk 1]
```diff
@@ -599,9 +599,9 @@ const editorReducer = (state = {}, action) => {
       const currentPatchPath = currentTab.patchPath;
       const currentOffset = currentTab.offset;
       return R.compose(
+        setTabOffset(currentOffset, DEBUGGER_TAB_ID),
```
Comment (nkrkv) [inline packages/xod-client/src/editor/reducer.js]: Could you explain the magic? I can’t understand why order matters here.
