### PR TITLE
Make proper errors for different steps of upload process

### LINKED ISSUE #1478: Misleading error message if compilation fails
For an example, see a [post on the forum](https://forum.xod.io/t/stm32f103c-blue-pill-port-literals/1239).

### Steps to reproduce

1. Create a project with the `main` patch having `digital-write` on it
2. Go break C++ code of `digital-write`: introduce some intentional syntax errors
3. Switch to `main` and Deploy → Upload to Arduino

### Expected behavior

A message about errors in C++ is shown:

`C:\Users\OPTIPL~1\AppData\Local\Temp\xod_temp_sketchbook1WFQV1\xod_1539803363197_sketch\xod_1539803363197_sketch.ino: In function ‘void xod::xod__gpio__digital_write::evaluate(xod::xod__gpio__digital_write::Context)’:
C:\Users\OPTIPL~1\AppData\Local\Temp\xod_temp_sketchbook1WFQV1\xod_1539803363197_sketch\xod_1539803363197_sketch.ino:1238:24: error: ‘NUM_DIGITAL_PINS’ was not declared in this scope`
`bool err = (port > NUM_DIGITAL_PINS - 1);`
`^`

`Error: exit status 1`
`Compilation failed.`
~Upload tool exited with error~
`Command C:\Program Files\XOD IDE\resources\arduino-cli.exe --config-file=C:\Users\OPTIPL~1\AppData\Local\Temp\arduino-cliUqQlfe\.cli-config.yml compile --fqbn stm32duino:STM32F1:genericSTM32F103C:upload_method=DFUUploadMethod C:\Users\OPTIPL~1\AppData\Local\Temp\xod_temp_sketchbook1WFQV1\xod_1539803363197_sketch failed with code 1`
~`Make sure the board is connected, the cable is working, the board model set correctly, the upload port belongs to the board, the board drivers are installed, the upload options (if any) match your board specs.`~
`The generated C++ code contains errors. It can be due to a bad node implementation or if your board is not compatible with XOD runtime code. The original compiler error message is above. Fix C++ errors to continue. If you believe it is a bug, report the problem to XOD developers.`

### Actual behavior

A misguiding message related to the upload process is shown:

`C:\Users\OPTIPL~1\AppData\Local\Temp\xod_temp_sketchbook1WFQV1\xod_1539803363197_sketch\xod_1539803363197_sketch.ino: In function ‘void xod::xod__gpio__digital_write::evaluate(xod::xod__gpio__digital_write::Context)’:
C:\Users\OPTIPL~1\AppData\Local\Temp\xod_temp_sketchbook1WFQV1\xod_1539803363197_sketch\xod_1539803363197_sketch.ino:1238:24: error: ‘NUM_DIGITAL_PINS’ was not declared in this scope`
`bool err = (port > NUM_DIGITAL_PINS - 1);`
`^`

`Error: exit status 1`
`Compilation failed.`
`Upload tool exited with error`
`Command C:\Program Files\XOD IDE\resources\arduino-cli.exe --config-file=C:\Users\OPTIPL~1\AppData\Local\Temp\arduino-cliUqQlfe\.cli-config.yml compile --fqbn stm32duino:STM32F1:genericSTM32F103C:upload_method=DFUUploadMethod C:\Users\OPTIPL~1\AppData\Local\Temp\xod_temp_sketchbook1WFQV1\xod_1539803363197_sketch failed with code 1
Make sure the board is connected, the cable is working, the board model set correctly, the upload port belongs to the board, the board drivers are installed, the upload options (if any) match your board specs.`

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #1478

### CODE REVIEW

File: packages/xod-client-electron/src/app/arduinoCli.js [hunk 1]
```diff
@@ -209,6 +209,30 @@ const patchFqbnWithOptions = board => {
...
 };
 
+// =============================================================================
+//
+// Error wrappers
+//
+// =============================================================================
+
+// :: Error -> RejectedPromise Error
+const catchCompileError = err =>
```
Comment (nkrkv) [inline packages/xod-client-electron/src/app/arduinoCli.js]: Yes, they are error wrappers and should have names like `wrapCompileError`. Otherwise, they look misleading when used. One can think they recover from errors.

Comment (brusherru) [reply packages/xod-client-electron/src/app/arduinoCli.js]: 👌

File: packages/xod-client-electron/src/upload/messages.js [hunk 2]
```diff
@@ -4,6 +4,11 @@ export default {
     note: `Cloud compilation does not support ${boardName} yet.`,
     solution: 'Try to compile it on your own computer',
   }),
+  COMPILE_TOOL_ERROR: ({ message }) => ({
+    note: `Command ${message}`,
```
Comment (nkrkv) [inline packages/xod-client-electron/src/upload/messages.js]:
```suggestion
    title: 'Compilation failed',
    note: `Command ${message}`,
```
