### PR TITLE
Select all patch entities or input contents from menu item

### LINKED ISSUE #1497: Edit → Select All handles sidebar, not patch board
[Reported](https://forum.xod.io/t/select-all-in-menu-no-work/1261/2) on the forum.

### Environment

- Scope: desktop IDE
- Version: 0.25.1
- OS: Linux, Gnome 3

### Steps to reproduce

1. Ensure the Quick Help sidebar is open
2. Open patch `xod/datetime/am-pm`
3. Hit Edit → Select All

### Expected behavior

All nodes of the patch are selected

### Actual behavior

The gag text “Select a node or patch to view its documentation article” of Quick Help is selected.

### Extra details

If I click the patch board (to focus it) and then press Ctrl+A, all nodes get selected. However, if I would use the Select All menu item instead, Quick Help contents are selected again. Looks like the patch board loses its focus once I enter main menu.

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #1497.

Also, I've added "Select All" menu item into browser version of the IDE, that selects all entities on the Patch.

### CODE REVIEW

File: packages/xod-client-electron/src/view/containers/App.jsx [hunk 1]
```diff
@@ -575,7 +575,19 @@ class App extends client.App {
         items.cut,
         items.copy,
         items.paste,
-        items.selectall,
+        onClick(items.selectall, () => {
```
Comment (nkrkv) [inline packages/xod-client-electron/src/view/containers/App.jsx]: Too complex function for the purely structural code span. Suggest extracting it to a method

File: packages/xod-client-electron/src/view/containers/App.jsx [hunk 2]
```diff
@@ -575,7 +575,19 @@ class App extends client.App {
...
+          // We can't use `role: 'selectall'` here, cause it ignores `onClick`.
```
Comment (nkrkv) [inline packages/xod-client-electron/src/view/containers/App.jsx]: :scroll: because

File: packages/xod-client-browser/src/containers/App.jsx [hunk 3]
```diff
@@ -249,6 +249,8 @@ class App extends client.App {
         onClick(items.undo, this.props.actions.undoCurrentPatch),
         onClick(items.redo, this.props.actions.redoCurrentPatch),
         items.separator,
+        onClick(items.selectall, this.props.actions.selectAll),
+        items.separator,
```
Comment (nkrkv) [inline packages/xod-client-browser/src/containers/App.jsx]: This makes menu overflown. Also, a non-relevant in Linux command+A is shown

screenshot from 2018-10-25 12-31-16

**Comment by brusherru** [comment]
@nkrkv check it out, please

**Comment by brusherru** [comment]
@nkrkv Oops. My bad.
Moved function into App container method, but forget to `bind` it 🙈 
Fixed!

**Comment by brusherru** [comment]
@nkrkv finally, it has to work.
Tested on Ubuntu in Virtual Machine.

File: packages/xod-client/src/core/containers/App.jsx [hunk 4]
```diff
@@ -32,6 +33,25 @@ export default class App extends React.Component {
     this.transformProjectForTranspiler = this.transformProjectForTranspiler.bind(
       this
     );
+
+    /**
+     * We have to handle some hotkeys, because:
+     * - Browser IDE should prevent default event handling
+     * - Electron IDE could not handle correct some hotkeys.
```
Comment (nkrkv) [inline packages/xod-client/src/core/containers/App.jsx]: :scroll: Electron IDE cannot handle some hotkeys correctly
