### PR TITLE
Fix blurred vertical edges on Patch canvas

### LINKED ISSUE #1166: Vertical lines are blurred
### Steps to reproduce

1. Place a couple of nodes and connect them with a vertical link

### Expected behavior

Node borders and the link line render pixel-perfectly

### Actual behavior

Horizontal lines are OK, vertical lines are moired

screenshot from 2018-04-20 12-58-59

### How to fix

For some reason the root SVG `<g>` gets `transform=matrix(1, 0, 0, 1, 385.5, 496)`. Note the fractional X-offset. If should be always rounded.

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #1166.

### CODE REVIEW

File: packages/xod-client/src/editor/containers/Patch/modeUtils.js [hunk 1]
```diff
@@ -3,7 +3,14 @@ import * as R from 'ramda';
 export const bindApi = (api, fn) => (...args) => fn(api, ...args);
 
 // :: Point -> String
-export const getOffsetMatrix = ({ x, y }) => `matrix(1, 0, 0, 1, ${x}, ${y})`;
+export const getOffsetMatrix = ({ x, y }) =>
+  `matrix(1, 0, 0, 1, ${Math.round(x)}, ${Math.round(y)})`;
+
+// :: Point -> Point
+export const roundOffsetToPixel = R.compose(
```
Comment (nkrkv) [inline packages/xod-client/src/editor/containers/Patch/modeUtils.js]: It’s a function operating over `Point`’s (not limited to offsets). Is `roundPointToPixel` a better name? Just a bore.

File: packages/xod-client/src/editor/containers/Patch/modes/linking.jsx [hunk 2]
```diff
@@ -64,7 +69,7 @@ const linkingMode = {
             width={api.props.size.width}
             height={api.props.size.height}
             onClick={bindApi(api, this.onBackgroundClick)}
-            offset={api.props.offset}
+            offset={roundOffsetToPixel(api.props.offset)}
```
Comment (nkrkv) [inline packages/xod-client/src/editor/containers/Patch/modes/linking.jsx]: A lot of error-prone code duplication. I suggest postponing rounding as long as possible, for example, do it once in `BackgroundLayer.jsx` → `NodeSlotPattern`
